name: Hello world workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
	- uses: actions/checkout@v3
    	- name: goodbye hello world
	  run: echo "Goodbye hello world"
	  shell: bash

  goodbye:
    runs-on: ubuntu-latest

    steps:
    	- name: goodbye hello world
	  run: echo "Goodbye hello world"
	  shell: bash
